Document available services and their routes
MiSArch/docs pull request #15
Opened 2023-12-06 18:24 UTC by delvh

2023-12-06 18:47 UTC, lesser1 commented on docs/dev-manuals/architecture/services.md
> +
Why is this a numerical list but every item of it starts at 1.?

2023-12-06 19:55 UTC, nk-coding commented on docs/dev-manuals/architecture/services.md
> +
In the rendered version, markdown automatically increases the number. This makes maintaining the source easier

2023-12-06 19:56 UTC, nk-coding commented on docs/dev-manuals/architecture/services.md
> +# Services
where is the position meta data stuff?

2023-12-06 20:39 UTC, lesser1 commented on docs/dev-manuals/architecture/services.md
> +
That's awesome! I like it

2023-12-06 20:54 UTC, legendofa requested changes
It might be more easy to first create API endpoints for the resources that are fundamental for each service. Also each parent folder should be a plural: `review -> reviews` For example: 

Review service: `/reviews/<id>`
Payment service: `payments/<id>`, `payment-providers/<id>`

And then build user based functionality upon that, if necessary:

Review service: `users/<username>/reviews/<id>`
Payment service: `users/<username>/payments/<id>`, `payment-providers/id`

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - CRUD on `/products`, CRUD on `/products/<product>/variants`
How to query different product variant versions?

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - Stores available discounts per user and/or product
Must store both `Coupon` and `Discounts` and enable CRUD

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - stores the available categories of items
```suggestion
   - stores the available categories of products
```

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - stores items that are in the pending order (the next one to be bought)
Why pending order? I think the order only matters to display which items were added first

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - routes `/account/register`, `/account/login`, \<TODO: Path to query JWT token of a user\>
How about adding `/accounts` to query all accounts for admin purposes?

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - routes `/user/<username>/notifications?state=<state>`, `/user/<username>/notifications/<notification>/change-read`
```suggestion
   - routes `/user/<username>/notifications?isRead=<state>`, `/user/<username>/notifications/<notification>/isRead=<state>`
```

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - routes `/user/<username>/addresses`
Addresses should be queried without a reference to the user, as they are used for orders/returns, etc. I would suggest an ID:

```suggestion
   - routes `/address/<id>`, `/addresses`
```

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +1. Review
What about querying the reviews of a specific user: `/user/<username>/reviews`

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - routes: CRUD on `/taxes`
```suggestion
  - routes: CRUD on `/tax-rates`
```

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +1. Tax
How about querying different tax rate versions?

2023-12-06 20:54 UTC, legendofa commented on docs/dev-manuals/architecture/services.md
> +   - routes: CRUD on `/payment/providers`, CRUD on `/user/<username>/payments`, `/payments/<payment>/receipt`
I am not sure if we should query `providers` under `payment`. It this is the case then `payment` should also return a useful resource

2023-12-12 16:09 UTC, legendofa commented
I guess this is now deprecated with GraphQL Federation, shall we close it?

2023-12-14 09:31 UTC, delvh commented
I still need to update it.
After all, such an overview is still necessary, but better.

2024-01-10 16:30 UTC, closed without merging